### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by blubkens** [internetkultur-ab/ipsw-downloader#1]
When trying to pull the new ipsw for the latest iPhones i run in to the following error.

`Traceback (most recent call last):
  File "/Users/users/Downloads/ipsw-downloader-master/ipsw-downloader.py", line 76, in <module>
    latest_available_files.append(response_body['firmwares'][0]['url'].rsplit('/', 1)[-1])
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range`

Not sure if i'm missing something.
Are you able to guide me in the correct direction?


This is the identifier list:

`# Specify what devices to include
identifiers = ['iPhone13,2','iPhone14,4','iPhone14,5','iPhone14,6','iPhone14,7','iPhone14,8','iPhone15,2','iPhone15,4','iPhone15,5','iPhone16,1','iPhone16,2','iPhone15,3','iPad14,3','iPad13,18','iPad13,19','iPad13,16','iPad13,17','iPad14,1','iPad14,6','iPad14,2','iPad12,1','iPad12,2','MacBookPro18,2']
`

**Comment by nilssonalex** [comment]
Hm, the ipsw.me API does not respond with any firmwares for the new iPhones and my script has no error handling. 
https://api.ipsw.me/v4/device/iPhone15,4
https://api.ipsw.me/v4/device/iPhone15,5
https://api.ipsw.me/v4/device/iPhone16,1
https://api.ipsw.me/v4/device/iPhone16,2

**Comment by blubkens** [comment]
It does show it directly on the site but it appears the API might not have been updated.

`https://ipsw.me/download/ota/iPhone16,2/21A6331?prerequisite=`

**Comment by nilssonalex** [comment]
Yeah it's a bit weird. On the page before that it says it's a beta version.

**Comment by blubkens** [comment]
Officially it is not the 22nd yet so i might be jumping the gun here?

**Comment by nilssonalex** [comment]
I think so :) your list works fine when removing the four new devices. One day i'll code in some error handling but for now this is as good as it gets.

**Comment by blubkens** [comment]
Just quickly wanted to thank you for your work, the tool is awesome and i use it very often at work :D

**Comment by nilssonalex** [comment]
Happy to hear that :)

**Comment by blubkens** [comment]
Confirming that i jumped the gun and it is working perfectly now. Have a good weekend.
